// ── EXPORT CSV ────────────────────────────────────────────
function exportCSV() {
  const data = AppState.cleanData || AppState.rawData;
  if (!data) { alert('No data to export.'); return; }

  const csv = Papa.unparse(data);
  downloadFile(csv, 'text/csv', `cleaned_${AppState.fileName || 'data.csv'}`);
  showReportStatus('✅ CSV exported successfully!');
}

// ── EXPORT JSON ───────────────────────────────────────────
function exportJSON() {
  const data = AppState.cleanData || AppState.rawData;
  if (!data) { alert('No data to export.'); return; }

  const json = JSON.stringify({ meta: { rows: data.length, columns: AppState.columns, file: AppState.fileName }, data }, null, 2);
  downloadFile(json, 'application/json', `data_${Date.now()}.json`);
  showReportStatus('✅ JSON exported successfully!');
}

// ── EXPORT HTML REPORT ────────────────────────────────────
function exportReport() {
  const data = AppState.cleanData || AppState.rawData;
  if (!data) { alert('No data to export.'); return; }

  const numCols = getNumericColumns();
  const statsRows = numCols.map(col => {
    const vals = data.map(r => parseFloat(r[col])).filter(v => !isNaN(v));
    if (!vals.length) return '';
    const sorted = [...vals].sort((a, b) => a - b);
    const mean = vals.reduce((a, b) => a + b, 0) / vals.length;
    const median = sorted[Math.floor(sorted.length / 2)];
    const std = Math.sqrt(vals.map(v => (v - mean) ** 2).reduce((a, b) => a + b, 0) / vals.length);
    return `<tr><td>${col}</td><td>${vals.length}</td><td>${mean.toFixed(2)}</td><td>${median.toFixed(2)}</td><td>${std.toFixed(2)}</td><td>${sorted[0]}</td><td>${sorted[sorted.length-1]}</td></tr>`;
  }).join('');

  const sampleRows = data.slice(0, 10).map(r =>
    `<tr>${AppState.columns.map(c => `<td>${r[c] ?? ''}</td>`).join('')}</tr>`
  ).join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Data Analysis Report — ${AppState.fileName}</title>
<style>
  body{font-family:'Segoe UI',sans-serif;background:#0f1115;color:#e0e0e0;padding:2rem;max-width:1000px;margin:0 auto}
  h1{color:#5b8ff9;font-size:28px;margin-bottom:0.25rem}
  h2{color:#a78bfa;font-size:18px;margin:2rem 0 1rem;border-bottom:1px solid #2a2e38;padding-bottom:0.5rem}
  .meta{color:#666;font-size:14px;margin-bottom:2rem}
  .stats-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin-bottom:2rem}
  .stat{background:#1a1e25;border-radius:10px;padding:1rem}
  .stat-label{font-size:11px;color:#555;text-transform:uppercase;letter-spacing:0.07em}
  .stat-value{font-size:24px;font-weight:600;color:#5b8ff9;font-family:monospace}
  table{width:100%;border-collapse:collapse;font-size:13px;margin-bottom:2rem}
  th{background:#1a1e25;color:#666;padding:8px 10px;text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:0.05em}
  td{padding:7px 10px;border-bottom:1px solid #1e2229;font-family:monospace;color:#9ba3b0}
  tr:hover td{background:#1a1e25}
  .insights{background:#1a1e25;border-left:3px solid #a78bfa;border-radius:8px;padding:1.25rem;white-space:pre-wrap;font-size:13px;line-height:1.75;color:#9ba3b0;font-family:monospace}
  .no-insights{color:#444;font-style:italic;padding:1rem}
  .footer{margin-top:3rem;padding-top:1rem;border-top:1px solid #1e2229;color:#333;font-size:12px}
</style>
</head>
<body>
<h1>📊 Data Analysis Report</h1>
<div class="meta">File: ${AppState.fileName} · Generated: ${new Date().toLocaleString()} · Model: ${AppState.model || 'N/A'}</div>

<h2>Overview</h2>
<div class="stats-grid">
  <div class="stat"><div class="stat-label">Total Rows</div><div class="stat-value">${data.length.toLocaleString()}</div></div>
  <div class="stat"><div class="stat-label">Columns</div><div class="stat-value">${AppState.columns.length}</div></div>
  <div class="stat"><div class="stat-label">Numeric</div><div class="stat-value">${numCols.length}</div></div>
  <div class="stat"><div class="stat-label">Categorical</div><div class="stat-value">${getCategoricalColumns().length}</div></div>
</div>

${numCols.length ? `
<h2>Statistical Summary</h2>
<table>
  <thead><tr><th>Column</th><th>Count</th><th>Mean</th><th>Median</th><th>Std Dev</th><th>Min</th><th>Max</th></tr></thead>
  <tbody>${statsRows}</tbody>
</table>` : ''}

<h2>Sample Data (first 10 rows)</h2>
<table>
  <thead><tr>${AppState.columns.map(c => `<th>${c}</th>`).join('')}</tr></thead>
  <tbody>${sampleRows}</tbody>
</table>

<h2>AI Insights</h2>
${AppState.aiInsights
  ? `<div class="insights">${AppState.aiInsights}</div>`
  : '<div class="no-insights">No AI insights generated yet. Run AI Analysis first.</div>'}

<div class="footer">Generated by AI Data Analysis Automation · Powered by Groq API (Llama / Mixtral)</div>
</body>
</html>`;

  downloadFile(html, 'text/html', `report_${AppState.fileName?.replace(/\.[^.]+$/, '') || 'analysis'}.html`);
  showReportStatus('✅ HTML Report exported! Open it in any browser.');
}

// ── DOWNLOAD HELPER ───────────────────────────────────────
function downloadFile(content, mimeType, fileName) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function showReportStatus(msg) {
  const el = document.getElementById('reportStatus');
  if (el) {
    el.innerHTML = `<div style="margin-top:1rem;padding:0.75rem 1rem;background:rgba(52,211,153,0.08);border:1px solid rgba(52,211,153,0.2);border-radius:8px;font-size:13px;color:var(--success)">${msg}</div>`;
    setTimeout(() => { if (el) el.innerHTML = ''; }, 4000);
  }
}
